### Create a new order
POST http://localhost:3001/api/orders
Content-Type: application/json

{
    "userId": "66df04d942336b091163a777",
    "products": [
        {
            "productId": "66df04e642336b091163a779",
            "quantity": 2
        },
        {
            "productId": "66df04f142336b091163a77c",
            "quantity": 1
        }
    ]
}

### Get order by ID
GET http://localhost:3001/api/orders/67299fa0d65c7fb6c9a369bc

### Update order status
PUT http://localhost:3001/api/orders/672a371873e06f6364d707a2
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3MmExZmE1OGNhNzYwMDAzNDNmN2UzMyIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTczMDgxOTkxMiwiZXhwIjoxNzMwODIzNTEyfQ.iwt7EtfOm_VRn43yg7g7OFJVUHvtQsWpcD5TOsySDCw

{
    "status": "Pending"
}

### Delete order by ID
DELETE http://localhost:3001/api/orders/66d9ae776e986b72bc744d96
