### Add a New Product
POST http://localhost:3001/api/products
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3MmExZmE1OGNhNzYwMDAzNDNmN2UzMyIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTczMDgxNDU5MywiZXhwIjoxNzMwODE4MTkzfQ.t6WkqZQPD3GYDsd4BR8xuQdIccV29YE56Hhd-aikJe8

{
    "name": "SUPREME JACKET",
    "rating": 4.5,
    "numOfReviews": 100,
    "basePrice": 50.00,
    "discountRate": 10,
    "productImage": "http://example.com/product.png",
    "variations": [
        {
            "variationName": "Size-Color",
            "size": "M",
            "color": "Blue",
            "price": 55.00,
            "discountRate": 5,
            "image": "http://example.com/variation1.png"
        }
    ],
    "imagesVariation": [
        "http://example.com/variation1.png",
        "http://example.com/variation2.png"
    ]
}

### Get Product by ID
GET http://localhost:3001/api/products/672f0bde403cd46181ff511e
Content-Type: application/json

### Get All Products
GET http://localhost:3001/api/products/
Content-Type: application/json


### Delete Product by ID
DELETE http://localhost:3001/api/products/66d9acdc2fe756f08fe79e56
Content-Type: application/json


### Update Product by ID
PUT http://localhost:3001/api/products/672a228c8472da6e83e988ea
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3MmExZTgxZmJkZjZjOTc4ODU4ODQ3OSIsInJvbGUiOiJ1c2VyIiwiaWF0IjoxNzMwODE0NzIxLCJleHAiOjE3MzA4MTgzMjF9.OJ2KTjCBnA1K5A8rRjyEVlllb1lh19PXZGKl9648HJI

{
    "name": "Updated Product",
    "rating": 4.8,
    "numOfReviews": 120,
    "basePrice": 60.00,
    "discountRate": 15,
    "productImage": "http://example.com/updated_product.png",
    "variations": [
        {
            "variationName": "Size-Color",
            "size": "L",
            "color": "Red",
            "price": 65.00,
            "discountRate": 10,
            "image": "http://example.com/updated_variation.png"
        }
    ],
    "imagesVariation": [
        "http://example.com/updated_variation.png"
    ]
}
