### Create a new user
POST http://localhost:3001/api/users
Content-Type: application/json

{
    "username": "user",
    "name": "John Doe",
    "password": "password"
}

### Get all users
GET http://localhost:3001/api/users



### Add product to user's cart
POST http://localhost:3001/api/users/cart/add
Content-Type: application/json

{
    "userId": "66e023bdcb8c331914184038",
    "productId": "66e023c5cb8c33191418403a",
    "quantity": 2
}

### Remove product from user's cart
POST http://localhost:3001/api/users/cart/remove
Content-Type: application/json

{
    "userId": "66d9ae776e986b72bc744d96",
    "productId": "66d9aec76e986b72bc744da7"
}

### Clear user's cart
POST http://localhost:3001/api/users/cart/clear
Content-Type: application/json

{
    "userId": "66d9ae776e986b72bc744d96"
}
