### Create a new user
POST https://shopify-clone-odra.onrender.com/api/users
Content-Type: application/json

{
    "username": "user@user.com",
    "name": "username",
    "password": "password"
}


### LOGIN
POST http://localhost:3001/api/login
Content-Type: application/json

{
    "username": "user@user.com",
    "password": "password"
}

### Get all users
GET https://shopify-clone-odra.onrender.com/api/users/



### Add product to user's cart
POST http://localhost:3001/api/users/cart/add
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3MmExZTgxZmJkZjZjOTc4ODU4ODQ3OSIsInJvbGUiOiJ1c2VyIiwiaWF0IjoxNzMwODE4MDY2LCJleHAiOjE3MzA4MjE2NjZ9.4ghhxmi0HiNQedCbaKstryo_zWch-TlITEhzStM2F98

{
    "productId": "672a228c8472da6e83e988ea",
    "quantity": 2
}

### Remove product from user's cart
POST http://localhost:3001/api/users/cart/remove
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3MmExZTgxZmJkZjZjOTc4ODU4ODQ3OSIsInJvbGUiOiJ1c2VyIiwiaWF0IjoxNzMwODE4MDY2LCJleHAiOjE3MzA4MjE2NjZ9.4ghhxmi0HiNQedCbaKstryo_zWch-TlITEhzStM2F98

{
    "productId": "672a228c8472da6e83e988ea"
}

### Clear user's cart
POST http://localhost:3001/api/users/cart/clear
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3MmExZTgxZmJkZjZjOTc4ODU4ODQ3OSIsInJvbGUiOiJ1c2VyIiwiaWF0IjoxNzMwODE4MDY2LCJleHAiOjE3MzA4MjE2NjZ9.4ghhxmi0HiNQedCbaKstryo_zWch-TlITEhzStM2F98


### Get user's cart
GET http://localhost:3001/api/users/cart/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3MmExZTgxZmJkZjZjOTc4ODU4ODQ3OSIsInJvbGUiOiJ1c2VyIiwiaWF0IjoxNzMwODE4MDY2LCJleHAiOjE3MzA4MjE2NjZ9.4ghhxmi0HiNQedCbaKstryo_zWch-TlITEhzStM2F98

