### Create a new user
POST http://localhost:3001/api/users
Content-Type: application/json

{
    "username": "user",
    "name": "John Doe",
    "password": "password"
}

### Get all users
GET http://localhost:3001/api/users/cart?userId=66ebdec5e6fb5ea87ce16f92



### Add product to user's cart
POST http://localhost:3001/api/users/cart/add
Content-Type: application/json

{
    "userId": "66ebdec5e6fb5ea87ce16f92",
    "productId": "66ec0babc9db96a273e5da39",
    "quantity": 2
}

### Remove product from user's cart
POST http://localhost:3001/api/users/cart/remove
Content-Type: application/json

{
    "userId": "66d9ae776e986b72bc744d96",
    "productId": "66d9aec76e986b72bc744da7"
}

### Clear user's cart
POST http://localhost:3001/api/users/cart/clear
Content-Type: application/json

{
    "userId": "66d9ae776e986b72bc744d96"
}
